AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB

Resources:
  DDBContractTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cng-contract
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: walletAddress
          AttributeType: S
        - AttributeName: walletAddress_schema
          AttributeType: S
        - AttributeName: ipfsImageHash
          AttributeType: S
        - AttributeName: glk
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: walletAddress-createdAt-index
          KeySchema:
            - AttributeName: walletAddress
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: walletAddress_schema-createdAt-index
          KeySchema:
            - AttributeName: walletAddress_schema
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: pk-ipfsImageHash-index
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: ipfsImageHash
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: glk-createdAt-index
          KeySchema:
            - AttributeName: glk
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: pk-createdAt-index
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1